name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests mapping
        run: python3 -m unittest unit_tests/mapping_module/TestMappingModule.py
      - name: Run tests middle
        run: python3 -m unittest unit_tests/middle_module/TestMiddleModule.py
      - name: Run tests EtuProgram
        run: python3 -m unittest unit_tests/models/Program/TestEtuProgram.py
      - name: Run tests RanepaProgram
        run: python3 -m unittest unit_tests/models/Program/TestRanepaProgram.py
      - name: Run tests SpbuProgram
        run: python3 -m unittest unit_tests/models/Program/TestSpbuProgram.py
      - name: Run tests EtuUniversity
        run: python3 -m unittest unit_tests/models/University/EtuUniversity/TestEtuUniversity.py
      - name: Run tests RanepaUniversity
        run: python3 -m unittest unit_tests/models/University/RanepaUniversity/TestRanepaUniversity.py
      - name: Run tests SpbuUniversity
        run: python3 -m unittest unit_tests/models/University/SpbuUniversity/TestSpbuUniversity.py  
